fixed broken install in docker file
stefanprodan/hrval-action pull request #52
Opened 2020-12-10 07:54 UTC by maorgoldberg

Fixed issue that caused curl version to break the docker file by updating its version.

2020-12-10 08:00 UTC, stefanprodan requested changes

2020-12-10 08:00 UTC, stefanprodan commented on Dockerfile
> +RUN apk --no-cache add curl==7.67.0-r2 bash==5.0.11-r1 git==2.24.3-r0 openssh-client==8.1_p1-r0
Can you please remove the version pinning for all packages

2020-12-10 11:07 UTC, maorgoldberg commented
Removing version pinning causes checks to fail

2020-12-10 11:25 UTC, stefanprodan commented
That lint rule is kinda silly, we need to remove it.

2020-12-10 11:29 UTC, maorgoldberg commented
Yea I'll take a look at the linting action and add an ignore for it and create a separate pr for it. However this one should fix dockerfile errors without issue regardless of the failed lint

2020-12-10 11:35 UTC, stefanprodan approved these changes
LGTM

Thanks @maorgoldberg

2020-12-10 11:36 UTC, merged

2020-12-15 00:09 UTC, stevenpall commented
Could we please get a new release cut that includes this fix? We try not to use `@master`.

2020-12-15 08:46 UTC, maorgoldberg commented
> Could we please get a new release cut that includes this fix? We try not to use `@master`.

Is an action needed on my part?

2020-12-17 21:06 UTC, stevenpall commented
> > Could we please get a new release cut that includes this fix? We try not to use `@master`.
> 
> Is an action needed on my part?

Nope, all good now. The `v3.5.0` release includes this fix. Thanks!